![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [3]:
my_array = np.arange(0,10)
my_array
print(my_array[9:0:-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [4]:
print(my_array[-3:-1][::-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [5]:
print(my_array[:3:][::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [32]:
matrix = np.arange(1,21)
matrix = matrix.reshape((4,5))
inverted_matrix = matrix[::-1,::-1]
print(inverted_matrix)


[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [38]:
matrix = np.arange(1,21)
matrix = matrix.reshape((4,5))
print(matrix)
print()
print("La solución es: ")
# ex5 = 
print(matrix[:2,:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

La solución es: 
[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [46]:
matrix = np.arange(1,21)
matrix = matrix.reshape((4,5))
print(matrix)
print()
print("La solución es:")
print(matrix[::2][::,::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

La solución es:
[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [3]:
matrix = np.arange(1,21)
matrix = matrix.reshape((4,5))
print(matrix)
print()
print("La solución es:")
print(matrix[:3:,::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

La solución es:
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [51]:
# Haciendo uso de máscaras
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
mascara = x == "Loro"
print(x[mascara])


['Loro' 'Loro']


In [53]:
# Haciendo uso de extract
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
mascara = x == "Loro"
extraction = np.extract(mascara,x)
print(extraction)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [56]:
ex9 = np.arange(1,21).reshape((2,5,2))
print(ex9)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [65]:
matrix = np.arange(1,21)
matrix = matrix.reshape((4,5))
matrix[::-1][::,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [79]:
ex11 = np.full((10),0)
print(ex11.nbytes)
print(ex11.itemsize)
ex11[3] = 1
print(ex11)

80
8
[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [88]:
ex12 = np.arange(10,50)
print(ex12)
ex12 = ex12[::-1]
print()
print(ex12)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [97]:
vector = np.array([1,2,0,0,4,0])
solution = np.argwhere(vector).reshape((1,-1))
print(solution)

[[0 1 4]]


In [4]:
np.argwhere??

Signature:       np.argwhere(a)
Call signature:  np.argwhere(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function argwhere at 0x000001D940454940>
File:            c:\users\usuario\miniconda3\envs\data_analysis_env\lib\site-packages\numpy\_core\numeric.py
Source:         
@array_function_dispatch(_argwhere_dispatcher)
def argwhere(a):
    """
    Find the indices of array elements that are non-zero, grouped by element.

    Parameters
    ----------
    a : array_like
        Input data.

    Returns
    -------
    index_array : (N, a.ndim) ndarray
        Indices of elements that are non-zero. Indices are grouped by element.
        This array will have shape ``(N, a.ndim)`` where ``N`` is the number of
        non-zero items.

    See Also
    --------
    where, nonzero

    Notes
    -----
    ``np.argwhere(a)`` is almost the same as ``np.transpose(np.nonzero(a))``,
    but produces a result of the correct shape for a 0D array.

    The output of ``

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [7]:
matrix14 = np.random.randint(0,100,(10,10))
print(matrix14)
print(matrix14.max())
print(matrix14.min())

[[17 12 60 57 78 40 82 21 94 91]
 [87 56 52  4 58  6 36 88 90 91]
 [66  9 61 49 14  0 27 49 96 59]
 [61 56 14 59 49 10 67 86 17 26]
 [73 16 50 30 92 34 63 88 30 37]
 [58 29 48 66 12 58 62 22  5 36]
 [97 69 69 42 95 27 82 62 39 51]
 [67 71 84 43 50 80 43 27 75 23]
 [12 34 14 98 37 24 45 96 63  4]
 [27 48 15 91 51 56 49 16 11  6]]
98
0


In [8]:
np.random.randn??

Signature: np.random.randn(*args)
Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned 

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [119]:
matrix14 = np.random.randint(0,10,(30))
print(matrix14)
print()
print("La solución es:")
print(matrix14.mean())

[7 0 0 4 9 1 1 2 1 9 5 3 4 7 7 7 7 9 9 8 2 3 6 1 1 1 7 5 6 8]

La solución es:
4.666666666666667


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [132]:
ex16 = np.ones((6,6))
print(ex16)
print()
print("La solución es:")
ex16[1:5][::,1:5:] = 0
print(ex16)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

La solución es:
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [171]:
ex17 = np.zeros((8,8))
ex17[::2,1::2] = 1
ex17[1::2,::2] = 1
print(ex17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [190]:
a = np.array([[0, 1], [1, 0]])
solution = np.tile(a,(4,4))
print(solution)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [191]:
# Ejemplo
b = np.array([[1, 2], [3, 4]])
np.tile(b, 2)
np.tile(b, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [195]:
ex19 = np.random.randint(0,10,(5,5))
print(ex19)
print()
print("La solución es:")
ex19_sol = (ex19 - ex19.mean()) / ex19.std()
print(ex19_sol)

[[9 1 0 3 3]
 [2 8 6 4 2]
 [6 8 1 9 2]
 [5 3 1 6 4]
 [6 1 7 0 8]]

La solución es:
[[ 1.67215923 -1.11477282 -1.46313933 -0.41803981 -0.41803981]
 [-0.76640632  1.32379273  0.62705971 -0.0696733  -0.76640632]
 [ 0.62705971  1.32379273 -1.11477282  1.67215923 -0.76640632]
 [ 0.27869321 -0.41803981 -1.11477282  0.62705971 -0.0696733 ]
 [ 0.62705971 -1.11477282  0.97542622 -1.46313933  1.32379273]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [240]:
seq = np.arange(0,11)
seq = 


[ 0  1  2  3  4  5  6  7  8  9 10]
[[ 0  1  2 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1  9 10]]


In [258]:
ex20 = np.arange(0,11)
print(ex20)
solution = np.where((3 <= ex20) & (ex20 <= 8), -1 , ex20)
print(solution)
ex20 = np.arange(0,11)
print(ex20)
mascara = (ex20 < 3) | (ex20 > 8)
solution2 = np.extract(mascara,ex20)
print(mascara)
print(solution2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ True  True  True False False False False False False  True  True]
[ 0  1  2  9 10]


In [212]:
np.any??

Signature:       np.any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)
Call signature:  np.any(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function any at 0x00000214CF139990>
File:            c:\users\usuario\miniconda3\envs\data_analysis_env\lib\site-packages\numpy\_core\fromnumeric.py
Source:         
@array_function_dispatch(_any_dispatcher)
def any(a, axis=None, out=None, keepdims=np._NoValue, *, where=np._NoValue):
    """
    Test whether any array element along a given axis evaluates to True.

    Returns single boolean if `axis` is ``None``

    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical OR reduction is performed.
        The default (``axis=None``) is to perform a logical OR over all
        the dimensions of the input array. `axis` may be negative, in
        which ca

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [2]:
# Creación de tablero 
tablero = np.full((10,10),"()")
tablero

array([['()', '()', '()', '()', '()', '()', '()', '()', '()', '()'],
       ['()', '()', '()', '()', '()', '()', '()', '()', '()', '()'],
       ['()', '()', '()', '()', '()', '()', '()', '()', '()', '()'],
       ['()', '()', '()', '()', '()', '()', '()', '()', '()', '()'],
       ['()', '()', '()', '()', '()', '()', '()', '()', '()', '()'],
       ['()', '()', '()', '()', '()', '()', '()', '()', '()', '()'],
       ['()', '()', '()', '()', '()', '()', '()', '()', '()', '()'],
       ['()', '()', '()', '()', '()', '()', '()', '()', '()', '()'],
       ['()', '()', '()', '()', '()', '()', '()', '()', '()', '()'],
       ['()', '()', '()', '()', '()', '()', '()', '()', '()', '()']],
      dtype='<U2')

In [83]:
# Posicionamiento de barcos
# Barco 1
tablero[0:2,1] = "O"
print(tablero)

print()
# Barco 2
tablero[1,4:8:] = "O"
print(tablero)




[['()' 'O' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' 'O' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']]

[['()' 'O' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' 'O' '()' '()' 'O' 'O' 'O' 'O' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']

In [3]:
# Por qué esto no funciona?
# Barco 1
barco_pequeno = tablero[0:2,1]
barco_pequeno = "O"
print(tablero)

print()
# Barco 2
barco_grande = tablero[1,4:8:]
barco_grande = "O"
print(tablero)


[['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']]

[['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '(

In [104]:
# Disparo a los barcos
# Barco pequeño
def canonazo():
    modo = input("¿En qué modo quieres jugar? (1 = Apuntando (Modo automático) / 2 = Apuntando (Modo Manual) / 3 = Aleatorio (Dispara a una posición aleatoria))")

    if modo == "1":
        disparo = input("¿Hacia donde quieres disparar? (s_ship (Barco pequeño) /l_ship (Barco grande) /Tu prima):")

        if disparo == "s_ship":
            if (tablero[0:2,1] == "X").all():
                print("¡Piedad, desgraciado! ¡Ya esta muerto!")
                return None
            else:
                print("¡Le has dado al barco pequeño!")
                tablero[0:2,1] = "X"

        elif disparo == "l_ship":
            if (tablero[1,4:8:] == "X").all():
                print("¡Piedad, desgraciado! ¡Ya esta muerto!")
                return None
            else:
                print("¡Le has dado al barco grande!")
                tablero[1,4:8:] = "X"

        elif disparo == "Tu prima":
            print("Jajaja, graciosillo, a las primas se les arrima, no se les dispara")
            return None
        else:
            print("Disparo al agua... Jack Sparrow estaría muy decepcionado")
            return None

        print(tablero)

    elif modo == "2":
        int_coor = input("Introduce las coordenadas a las que quieres disparar con el siguiente formato: (Fila,Columna)")
        coor_to_change = list((int_coor.replace("(","").replace(")","").replace(",","")))
        coor = []

        for number in coor_to_change:
            coor.append(int(number))
        
           

canonazo()

[1, 2]


In [92]:
print((tablero[0:2,1] == "X"))

[ True  True]


In [312]:
print((tablero[((0,1),(1,1))]).all())

True


In [103]:
coor_to_change = list(("(1,2)".replace("(","").replace(")","").replace(",","")))
coor = []

for number in coor_to_change:
    coor.append(int(number))

coor




[1, 2]